# Generated by Django 5.0.13 on 2025-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp_api', '0003_loandata_loan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_value', models.IntegerField()),
            ],
        ),
    ]
